# Generated by Django 4.2.6 on 2023-10-20 08:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utilities', '0002_fileupload'),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('entity_type', models.CharField(default='Note', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 20, 14, 22, 41, 756437), null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RenameField(
            model_name='task',
            old_name='version',
            new_name='version_number',
        ),
        migrations.AlterField(
            model_name='asset',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 20, 14, 22, 41, 744830), null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 20, 14, 22, 41, 744830), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 20, 14, 22, 41, 744830), null=True),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 20, 14, 22, 41, 744830), null=True),
        ),
        migrations.AlterField(
            model_name='shot',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 20, 14, 22, 41, 744830), null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 20, 14, 22, 41, 751755), null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 20, 14, 22, 41, 744830), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 20, 14, 22, 41, 752705), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 20, 14, 22, 41, 752688), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 20, 14, 22, 41, 744830), null=True),
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, null=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=None, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 20, 14, 22, 41, 744830), null=True)),
                ('version_number', models.IntegerField(default=1)),
                ('entity_type', models.CharField(default='Version', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.asset')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_created_by', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.episode')),
                ('media_files', models.ManyToManyField(blank=True, default=[], related_name='review_files', to='utilities.fileupload')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.project')),
                ('sequence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.sequence')),
                ('shot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.shot')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilities.status')),
                ('step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.step')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.task')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uid'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('entity_type', models.CharField(default='Reply', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 20, 14, 22, 41, 758336), null=True)),
                ('attachments', models.ManyToManyField(blank=True, default=[], to='utilities.fileupload')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_created_by', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.note')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.asset'),
        ),
        migrations.AddField(
            model_name='note',
            name='attachments',
            field=models.ManyToManyField(blank=True, default=[], to='utilities.fileupload'),
        ),
        migrations.AddField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='episode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.episode'),
        ),
        migrations.AddField(
            model_name='note',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.project'),
        ),
        migrations.AddField(
            model_name='note',
            name='sequence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.sequence'),
        ),
        migrations.AddField(
            model_name='note',
            name='shot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.shot'),
        ),
        migrations.AddField(
            model_name='note',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.step'),
        ),
        migrations.AddField(
            model_name='note',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.task'),
        ),
        migrations.AddField(
            model_name='note',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.version'),
        ),
    ]
