# Generated by Django 4.2.6 on 2023-10-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(error_messages={'unique': 'Email already exists.'}, help_text='Required. 250 characters or fewer. Letters, digits and @/./_ only.', max_length=250, unique=True),
        ),
    ]
